In [76]:
import numpy as np

# 1 d array

In [77]:
a=np.array([8,8,55,54,5,])
print(a)

[ 8  8 55 54  5]


In [78]:
type(a)

numpy.ndarray

In [79]:
# CREATING 2D ARRAY
a2=np.array([[1,2,3,4,5],[6,6,6,5,7]])
print(a2)

[[1 2 3 4 5]
 [6 6 6 5 7]]


In [80]:
# creatinG 3d array
a3=np.array([[[12,3,2],[5,6,8]],[[4,9,9],[4,5,5]]])
print(a3)

[[[12  3  2]
  [ 5  6  8]]

 [[ 4  9  9]
  [ 4  5  5]]]


In [81]:
print(a2.shape)

(2, 5)


In [82]:
print(a2.ndim)
print(a2.dtype)

2
int64


In [83]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [84]:
np.random.randint(1,11,size=(2,3))

array([[7, 4, 3],
       [6, 7, 5]], dtype=int32)

In [85]:
x=np.array([[4,5,5],
            [4,5,6],
            [1,2,3]])
y=np.array([[4,2,6],
            [4,5,6],
            [4,6,1]])
print(x)
print(y)

[[4 5 5]
 [4 5 6]
 [1 2 3]]
[[4 2 6]
 [4 5 6]
 [4 6 1]]


In [86]:
print(x@y)# matrix multiplication

[[56 63 59]
 [60 69 60]
 [24 30 21]]


In [87]:
np.dot(x,y) # matrix multiplication

array([[56, 63, 59],
       [60, 69, 60],
       [24, 30, 21]])

In [88]:
x.prod()# product of all elements of the array

np.int64(72000)

In [89]:
x.mean()

np.float64(3.888888888888889)

In [90]:
y.mean()

np.float64(4.222222222222222)

In [91]:
x.mean(axis=0) # column wise mean

array([3.        , 4.        , 4.66666667])

In [92]:
y.mean(axis=1) # row wise mean

array([4.        , 5.        , 3.66666667])

In [93]:
print(x.sum())
print(y.sum())
print(x.var())

35
38
2.3209876543209877


In [94]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) # 1st quartile
print(np.percentile(a,50)) # median
print(np.percentile(a,75))  # 3rd quartile

3.0
5.0
7.0


In [95]:
b=np.random.randint(11,100,(4,4))
print(b)

[[12 34 79 79]
 [48 61 22 29]
 [89 74 21 77]
 [84 68 17 31]]


In [96]:
x=np.random.randint(1,11,(5,5))
print(x)

[[ 7  8  7  8  6]
 [ 6  3  7 10  3]
 [ 2  6 10  9  7]
 [ 7 10 10  9  8]
 [10  6  3  1  2]]


In [97]:
print('2x8')
print(b.reshape(2,8))
print('8x2')
print(b.reshape(8,2))

2x8
[[12 34 79 79 48 61 22 29]
 [89 74 21 77 84 68 17 31]]
8x2
[[12 34]
 [79 79]
 [48 61]
 [22 29]
 [89 74]
 [21 77]
 [84 68]
 [17 31]]


In [98]:
print(x[0]) # 1st row
print(x[0,1])# 1st row and 2nd column s first elemrnt
print(x[-1])
print(x[:3])
print(x[3:])

[7 8 7 8 6]
8
[10  6  3  1  2]
[[ 7  8  7  8  6]
 [ 6  3  7 10  3]
 [ 2  6 10  9  7]]
[[ 7 10 10  9  8]
 [10  6  3  1  2]]
