In [1]:
import numpy as np

# 1 d array

In [6]:
a=np.array([8,8,55,54,5,])
print(a)

[ 8  8 55 54  5]


In [4]:
type(a)

numpy.ndarray

In [13]:
# CREATING 2D ARRAY
a2=np.array([[1,2,3,4,5],[6,6,6,5,7]])
print(a2)

[[1 2 3 4 5]
 [6 6 6 5 7]]


In [16]:
# creatinG 3d array
a3=np.array([[[12,3,2],[5,6,8]],[[4,9,9],[4,5,5]]])
print(a3)

[[[12  3  2]
  [ 5  6  8]]

 [[ 4  9  9]
  [ 4  5  5]]]


In [17]:
print(a2.shape)

(2, 5)


In [20]:
print(a2.ndim)
print(a2.dtype)

2
int64


In [23]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [24]:
np.random.randint(1,11,size=(2,3))

array([[6, 1, 8],
       [7, 3, 8]], dtype=int32)

In [ ]:
x=np.array([[4,5,5]
            [4,5,6]
            [1,2,3]
            ])
y=np.array([])